#!/usr/bin/env python3
"""Generate exact 256-entry colormap LUTs for the widget frontend.

This standalone script samples matplotlib's true colormaps at 256 evenly-spaced
points and computes a perceptually-uniform cyclic phase-wheel LUT using quantem's
JCh "domain coloring" (see
``quantem/src/quantem/core/visualization/visualization_utils.py:array_to_rgba``).

It emits ``js/colormap-data.ts`` consumed by ``js/colormaps.ts`` and
``js/showcomplex/index.tsx``. The frontend previously linearly interpolated a
handful of hand-typed control points — this produces the exact tables instead,
so the live canvas matches matplotlib (and ``showcomplex.py save_image``) exactly.

Usage:
    python scripts/gen_colormaps.py

Requires: matplotlib, colorspacious (and numpy).
"""

from __future__ import annotations

import pathlib

import numpy as np
from colorspacious import cspace_convert
from matplotlib import colormaps

# Colormap names exposed by js/colormaps.ts — keep this list in sync with
# COLORMAP_POINTS / the cmap dropdown in each widget.
COLORMAP_NAMES = [
    "inferno",
    "viridis",
    "plasma",
    "magma",
    "hot",
    "gray",
    "hsv",
    "turbo",
    "RdBu",
]

# Default chroma_boost used by quantem's array_to_rgba for domain coloring.
CHROMA_BOOST = 1.0

# Number of LUT entries (matches matplotlib's native table size and the widget
# normalization which maps data to a 0..255 index).
N = 256


def colormap_lut(name: str) -> list[int]:
    """Sample a matplotlib colormap at N evenly-spaced points -> flat RGB list.

    Returns a flat list of length N*3: [r0, g0, b0, r1, g1, b1, ...], each 0-255.
    """
    cmap = colormaps.get_cmap(name)
    samples = np.linspace(0.0, 1.0, N)
    rgba = cmap(samples)  # (N, 4) float in [0, 1]
    rgb = np.clip(np.round(rgba[:, :3] * 255.0), 0, 255).astype(int)
    return rgb.reshape(-1).tolist()


def jch_phase_wheel() -> list[int]:
    """Compute a cyclic 256-entry phase-wheel LUT via quantem's JCh coloring.

    Mirrors ``array_to_rgba`` with ``scaled_amplitude == 1`` (full lightness) so
    the wheel shows the pure hue ramp. The widget scales by amplitude on the JS
    side. Phase is sampled over a full turn [0, 2*pi); the table is cyclic so
    index 0 and index N wrap continuously.

    Returns a flat list of length N*3 (RGB, 0-255).
    """
    # scaled_angle in [-pi, pi) to match atan2 output used by the widget.
    angle = np.linspace(-np.pi, np.pi, N, endpoint=False)
    scaled_amplitude = np.ones(N)

    # JCh, identical math to visualization_utils.array_to_rgba (amplitude == 1).
    J = scaled_amplitude * 61.5
    C = np.minimum(CHROMA_BOOST * 98.0 * J / 123.0, 110.0)
    h = np.rad2deg(angle) + 180.0

    JCh = np.stack((J, C, h), axis=-1)
    with np.errstate(invalid="ignore"):
        rgb = cspace_convert(JCh, "JCh", "sRGB1").clip(0.0, 1.0)

    rgb255 = np.clip(np.round(rgb * 255.0), 0, 255).astype(int)
    return rgb255.reshape(-1).tolist()


def format_lut(values: list[int]) -> str:
    """Format a flat RGB list as a compact TS array literal (16 ints per line)."""
    lines = []
    for i in range(0, len(values), 48):  # 48 ints = 16 RGB triplets
        chunk = values[i : i + 48]
        lines.append("    " + ", ".join(str(v) for v in chunk) + ",")
    return "\n".join(lines)


def main() -> None:
    out_path = pathlib.Path(__file__).resolve().parent.parent / "js" / "colormap-data.ts"

    parts: list[str] = []
    parts.append(
        "// GENERATED by scripts/gen_colormaps.py — do not edit by hand.\n"
        "//\n"
        "// Exact 256-entry matplotlib colormap LUTs + a perceptually-uniform cyclic\n"
        "// JCh phase wheel (quantem domain coloring). Regenerate with:\n"
        "//   python scripts/gen_colormaps.py\n"
        "//\n"
        "// Each LUT is a flat RGB array of length 768 (256 entries * 3 channels),\n"
        "// values 0-255: [r0, g0, b0, r1, g1, b1, ...].\n"
    )

    # Colormap LUTs
    parts.append("export const COLORMAP_LUTS: Record<string, number[]> = {")
    for name in COLORMAP_NAMES:
        lut = colormap_lut(name)
        # Quote the key — RdBu is fine bare but quote uniformly for clarity.
        parts.append(f'  "{name}": [')
        parts.append(format_lut(lut))
        parts.append("  ],")
    parts.append("};")
    parts.append("")

    # JCh phase wheel
    wheel = jch_phase_wheel()
    parts.append(
        "// Cyclic phase-wheel LUT: 256 entries over phase [-pi, pi), JCh full\n"
        "// lightness. Index 0 == phase -pi, wraps continuously."
    )
    parts.append("export const JCH_PHASE_WHEEL: number[] = [")
    parts.append(format_lut(wheel))
    parts.append("];")
    parts.append("")

    out_path.write_text("\n".join(parts))
    print(f"Wrote {out_path} ({len(COLORMAP_NAMES)} colormaps + JCh phase wheel)")


if __name__ == "__main__":
    main()
